Repository S4ND1X/AtomicTracker, pull requests merged in 2021-12, with the labels that each got.

#26 Rework profile
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/DeleteAccountActivity.kt
  app/src/main/java/com/example/atomictracker/MainActivity.kt
  app/src/main/java/com/example/atomictracker/SignInActivity.kt
  app/src/main/java/com/example/atomictracker/UpdatePasswordActivity.kt
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_update_password.xml
Labels: enhancement

#30 UI rewok v1. done
  .idea/misc.xml
  app/src/main/res/drawable-v24/logo.png
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_buttom.xml
  app/src/main/res/drawable/ic_sign_out.xml
  app/src/main/res/layout/activity_delete_account.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/activity_update_password.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: UI

#32 feature migrate profile to new activity done
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/MainActivity.kt
  app/src/main/java/com/example/atomictracker/UserProfileActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_user_profile.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#33 feat create habit frontend
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/CreateHabitActivity.kt
  app/src/main/java/com/example/atomictracker/MainActivity.kt
  app/src/main/res/layout/activity_create_habit.xml
  app/src/main/res/values/spinner.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, frontend

#36 save habits on firebase
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/example/atomictracker/CreateHabitActivity.kt
  app/src/main/java/com/example/atomictracker/HabitDTO.kt
  build.gradle
Labels: enhancement, firebase

#37 Feat/list
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/HabitDTO.kt
  app/src/main/java/com/example/atomictracker/HabitListActivity.kt
  app/src/main/java/com/example/atomictracker/MainActivity.kt
  app/src/main/java/com/example/atomictracker/MyAdapter.kt
  app/src/main/res/layout/activity_habit_list.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/habit_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, firebase

#39 feature notification done using date and time
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/CreateHabitActivity.kt
  app/src/main/java/com/example/atomictracker/ReminderBroadcaster.kt
Labels: enhancement

#40 add README and LICENSE template
  LICENSE.txt
  README.md
  images/logo.png
  images/screenshot.png
Labels: documentation

#41 Feat/detail
  .idea/misc.xml
  README.md
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/DetailHabitActivity.kt
  app/src/main/java/com/example/atomictracker/HabitListActivity.kt
  app/src/main/java/com/example/atomictracker/MyAdapter.kt
  app/src/main/res/layout/activity_detail_habit.xml
  app/src/main/res/layout/habit_item.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#47 add facebook login done
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/atomictracker/MainActivity.kt
  app/src/main/java/com/example/atomictracker/SignInActivity.kt
  app/src/main/java/com/example/atomictracker/UserProfileActivity.kt
  app/src/main/res/drawable/facebook.png
  app/src/main/res/drawable/google.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, backend
